### ISSUE TITLE
Definir abonos de los clientes

### ISSUE THREAD

**Issue by edvm** [teritos/tero-saas#18]
Algunas métricas en:
http://media.ambito.com/diario/2017/0207/imagenes/not_872066_07_221157.jpg
http://www.ambito.com/872066-cuesta-hasta-us30000-blindar-una-casa-contra-la-ola-de-inseguridad

**Comment by jcarizza** [comment]
Una fortuna. Me gustó el servicio de *Simulación humana* xD jaja.

**Comment by edvm** [comment]
Agrego algunos servicios que brindan empresas locales:
https://www.adt.com.ar/images/uploads/ADT_Smart_Security_-_Manual_del_usuario_COMPLETO.pdf
https://www.adt.com.ar/?/adt-smart-security
https://play.google.com/store/apps/details?id=com.tdil.lojack.rl&hl=es
http://www.lanacion.com.ar/1981580-controla-todo-lo-que-pasa-en-tu-casa-desde-el-smartphone

**Comment by edvm** [comment]
Ya estan definidos! Quedamos en 3 lucas por mes
