### ISSUE TITLE
Hacer un hook para mensajes push

### ISSUE THREAD

**Issue by jcarizza** [teritos/tero-saas#25]
Hacer un hook en la aplicacion que cuando se reciba un mensaje push con cierto contenido se descargue una imagen o lo que fuere en la app.

**Comment by edvm** [comment]
No te cache Juan, me explicas con mas detalle? que hay que hacer? como es el tema?

**Comment by jcarizza** [comment]
Cuando se envía un mensaje desde tero-saas a un Device a travez de OneSignal se puede adjuntar un diccionario ej:
```
{
  'dato': 'valor',
  'dat1': 'valor1'
}
```

Cuando el Device recibe la notificación Push y la procesa con su callback [notificationOpenedCallback](https://documentation.onesignal.com/docs/ionic-sdk-setup#section-2-add-required-code) podes leer el diccionario de valores que te enviaron. Entonces dentro de la aplicación podes hacer lo que quieras en base a esa data.

Lo que habría que hacer es ver que en ese notificationOpenedCallback llegue algo de info para que podamos hacer algo con esa data.
