### ISSUE TITLE
Proteger las imágenes con token temporal

### ISSUE THREAD

**Issue by jcarizza** [teritos/tero-saas#27]
@edvm Podrá ser un token de UN acceso? Porque la aplicación necesita acceder a la imágen por URL.

**Comment by edvm** [comment]
Suena bien @jcarizza , googleando esto tiene pinta:
https://pypi.python.org/pypi/django-request-token/0.1.0
Queres lo implemente?

**Comment by jcarizza** [comment]
@edvm  me parece que nos podemos tirar por este lado más fácil. #36
