### ISSUE TITLE
Enviar imagenes a la app mobile

### ISSUE THREAD

**Issue by edvm** [teritos/tero-saas#28]
Cuando se genera un evento y llega una imagen desde las camaras, mandar la foto por OneSignal as in:
⁠⁠[11:43, 12/4/2017] Juan Carizza: ⁠⁠⁠Lo únito que tenemos que hacer para que la imágen llegué con la notificación es mandar una URL en el parametro big_picture del método onesignal.send_message(usuario, titulo, mensaje, big_picture=URLIMAGEN)
big_picture="%s%s" % (settings.DOMAIN, alarm_image.image.url)

**Comment by edvm** [comment]
Los estaticos de media los esta sirviendo nginx, se puede probar ej: https://tero.ninsei.tk/media/frula, el tema es que por ahora los AlarmImage no se estan guardando a disco (pareciera), osea no se guardan en el directorio media, aun no se bien porque, investigando...

**Comment by jcarizza** [comment]
Esto podríamos darlo por cerrado.
